### ISSUE TITLE
皮卡鱼引擎无法使用，cchess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)

### ISSUE THREAD

**Issue by ghost** [windshadow233/python-chinese-chess#6]
你好，代码是列出的例子
 ```
import cchess
import cchess.engine

engine = cchess.engine.SimpleEngine.popen_uci("/path/to/pikafish")
board = cchess.Board()
limit = cchess.engine.Limit(time=2.0)
engine.play(board, limit)
 ```
下载的是最新版的皮卡鱼（2024年8月31日的版本），报错如下。
 ```
File "D:\xiangqi\xiangqi.py", line 8, in <module>
    engine.play(board, limit)
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\z\AppData\Local\Programs\Python\Python313\Lib\site-packages\cchess\engine.py", line 2968, in play
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\z\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\z\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\z\AppData\Local\Programs\Python\Python313\Lib\site-packages\cchess\engine.py", line 1691, in play
    return await self.communicate(UciPlayCommand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z\AppData\Local\Programs\Python\Python313\Lib\site-packages\cchess\engine.py", line 1021, in communicate
    return await command.result
           ^^^^^^^^^^^^^^^^^^^^
cchess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)
 ```
bmi2、 avx2、popcnt的皮卡鱼都试过了，都是同样的错误。
谢谢

**Comment by windshadow233** [comment]
不好意思，这部分不是我开发的😂，可以问问那位贡献者～我这几天有点小忙，如果他迟迟不回复的话我等元旦后论文开完题研究一下。感谢您的反馈

**Comment by ghost** [comment]
谢谢。@shinoi2

**Comment by shinoi2** [comment]
@startnow2024 我这边测试没有问题，你可以尝试直接打开皮卡鱼的exe程序，输入uci，查看是否可以正常打开交互。
![image](https://github.com/user-attachments/assets/c7a72648-a9fd-4d26-9cc6-9c054baa07d5)

**Comment by shinoi2** [comment]
看你的报错应该是 pikafish 进程直接挂了，启动失败，应该是指令集问题。
皮卡鱼支持各种指令集，可先尝试“avx2”能否加载，不能加载则尝试“sse41-popcnt”。

**Comment by ghost** [comment]
@shinoi2 ，你好，谢谢回复。
bmi2、 avx2、sse41-popcnt，直接打开，都可以输入uci，显示成功，用上面列出的python代码，就不行。我的电脑是i7处理器，以前国际象棋的bmi、avx2的stockfish都能运行。

**Comment by shinoi2** [comment]
麻烦能提供一下python版本信息，pikafish版本

**Comment by ghost** [comment]
你好，可能是我没有设置nnue文件的原因。我刚输入bench测试，报错没有设置nnue路径，我放在同一个文件夹里不行。请问，用python上面代码的例子，怎么样设置nnue的路径？谢谢

**Comment by shinoi2** [comment]
将 nnue 和 pikafish 放在同一个文件夹内即可

**Comment by shinoi2** [comment]
直接下载解压的目录，测试脚本及目录接口参考
![image](https://github.com/user-attachments/assets/2c9db88d-34ad-4376-92fb-748680c74ab7)

**Comment by ghost** [comment]
不好意思，成功了，放在同一个文件夹里是可以的。我自己的文件和代码有点乱，看错了。谢谢

**Comment by shinoi2** [comment]
好的，新年快乐。

@windshadow233 麻烦close一下，以及https://github.com/windshadow233/python-chinese-chess/issues/2 也可以close。

**Comment by ghost** [comment]
问题就是，我下载压缩包的时候，没有把nnue的文件，复制到pikafish对应的文件夹里。谢谢

**Comment by ghost** [comment]
你也新年快乐

**Comment by ghost** [comment]
发现我测试的时候也没有完全看错了。我用的8月31版本的pikafish.exe, bench测试，报错没有nnue文件，我就下载了最新的，放在同一个文件夹里，报错。我复制pikafish压缩包的自带的8月31版本的nnue，放在同一个文件夹里，就可以。这里还有版本匹配的问题。谢谢了。
